var charector;
charector = 'ali';
var ali;
4;
var isBolean;
isBolean = false;
var ninjas;
// this not worh must edit to ninjas: string[]=[];
//ninjas.push('yoyo');
ninjas = ['aql', 'adsjo', 'oida'];
var numbers;
numbers = [3, 4, 6, 8];
var mixed;
mixed = [3, 'ali', 'yoyo'];
mixed.push(true);
console.log(mixed);
var uid;
uid = 87;
uid = 'saius';
var ninja;
ninja = { name: 'yoyo', age: 8 };
var ninjaTow;
ninjaTow.name = 'odoi';
ninjaTow.age = 4;
